Fines = {
    {label = 'Ebaseaduslik peatumine.', value = 1000, prison = 0},
    {label = 'Politseinikule vigastuse tekitamine.', value = 15000, prison = 15},
    {label = 'Signaali väärkasutamine', value = 500, prison =5},
    {label = 'Pideva joone ebaseaduslik ületamine', value = 150, prison = 0},
    {label = 'Vastassuunas sõitmine', value = 700, prison = 0},
    {label = 'Illegaalne U-Pööre', value = 300, prison = 0},
    {label = 'Ebaseaduslikult maastikul sõitmine', value = 5000, prison = 5},
    {label = 'Seaduslikust käsust keeldumine', value = 5000, prison =7},
    {label = 'Illegaalselt sõiduki peatamine', value = 5000, prison =0},
    {label = 'Illegaalne parkimine', value = 5000, prison =0},
    {label = 'Paremale pööramisel suuna mitte näitamine', value = 2500, prison =0},
    {label =  'Sõiduki Teabe mittejärgimine', value = 5000, prison = 5},
    {label =  'Stop märgi eiramine', value = 1500, prison = 0},
    {label =  'Punase tule taga mitte peatumine', value = 5000, prison = 5},
    {label =  'Illegaalne möödasõit', value = 750, prison =0},
    {label =  'Illegaalse autoga sõitmine', value = 1750, prison =0},
    {label =  'Ilma lubadeta sõitmine', value = 5000, prison =5},
    {label =  'Sündmuskohalt põgenemine', value = 5000, prison =8},
    {label =  'Kiiruse ületamine üle > 5 km/h', value =1500, prison =0},
    {label =  'Kiiruse ületamine üle 5-15 km/h', value = 2200, prison =0},
    {label =  'Kiiruse ületamine üle 15-30 km/h', value = 3000, prison =0},
    {label =  'Kiiruse ületamine üle > 30 km/h', value = 4500, prison =0},
    {label =  'Liikluse takistamine', value = 5000, prison = 0},
    {label =  'Avalik joove', value = 0, prison = 5},
    {label =  'Korratult käitumine', value =150, prison = 0},
    {label =  'Riigivara kahjustamine', value =6700, prison = 7},
    {label =  'Solvamine tsiviilisikute suhtes', value = 175, prison =0},
    {label =  'Politseiniku vastu lugupidamatus', value = 75, prison =0},
    {label =  'Suuline tsiviilisiku ähvardamine', value = 1525, prison =15},
    {label =  'Suuline politseiniku ähvardamine', value = 750, prison =0},
    {label =  'Valeteabe esitamine', value = 550, prison = 5},
    {label =  'Korruptsiooni katse', value = 1250, prison =9},
    {label =  'Surmava relva kasutamine linnapiirides', value =4750, prison =10},
    {label =  'Tulirelvast tule avamine relvaloa puudumisel', value =4570, prison =8},
    {label =  'Ebaseaduslike relvade omamine', value = 5000, prison = 5},
    {label =  'Ebaseaduslike tööriistade omamine', value = 1200, prison =12},
    {label =  'Autovargus Klass A', value =2500, prison = 5},
    {label =  'Ebaseadusliku aine valmistamine', value =6780, prison =15},
    {label =  'Ebaseadusliku aine omamine', value =2255, prison =13},
    {label =  'Ebaseadusliku aine müügi kavatsus', value = 5000, prison =22},
    {label =  'Tsiviilisiku röövimine', value = 5000, prison = 7},
    {label =  'Riigitöötaja röövimine', value = 7500, prison = 10},
    {label =  'Röövimine', value = 2500, prison = 7},
    {label =  'Poe relvastatud röövimine', value = 25000, prison = 20},
    {label =  'Panga relvastatud röövimine', value = 40000, prison = 30},
    {label =  'Relvastatud juveelipoe rööv', value = 32000, prison = 22},
    {label =  'Tsiviilisiku ründamine', value = 4000, prison = 7},
    {label =  'Riigitöötaja ründamine', value = 5000, prison = 10},
    {label =  'Tsiviilisiku mõrvakatse', value = 7500, prison = 7},
    {label =  'Riigitöötaja mõrva katse', value = 10000, prison = 10},
    {label =  'Tsiviilisiku mõrv', value = 15000, prison = 15},
    {label =  'Riigitöötaja mõrv', value = 20000, prison = 20},
    {label =  'Tahtlik tapmine', value = 10000, prison = 10},
    {label =  'Pettus', value = 5000, prison = 5},
    {label =  'Mõrv', value =9700, prison = 35},
    {label =  'Massimõrv', value =15000, prison =35},
    {label =  'Keelatud alal viibimine', value = 5000, prison =8},
    {label =  'Trahvide mittemaksmine', value =1000, prison =5},
    {label =  'Ebaseadusliku külmrelva omamine', value =850, prison =11}
    {label =  'Korruptsioon', value =0, prison =900}

};